version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
 build:
  docker:
   - image: circleci/golang:1.10
     
  steps:
   - checkout
   - setup_remote_docker
   #These environment variables are made available by CircleCI, either natively or
   #due to them being set in the project properties
   - run: echo ${CIRCLE_PROJECT_USERNAME} #Value is masked
   - run: echo ${DOCKER_REPO} #Value is masked
   - run: echo ${CIRCLE_PROJECT_REPONAME} #Value is masked
   #This one is already present in the container, most probably because it comes with the local installation of GO
   - run: echo ${GOPATH} #Resolves to /go
   
   ####################################################################################
   #This one is shown when invoking "go env", but from the system it is not set
   #- run: echo ${GOROOT} #Not set, prints empty value but should point to /usr/local/go
   
   # Each step is run under its own bash command, so the value is not available to other steps if done like this
   # - run: export GOROOT="/usr/local/go"
  
  # One method of carrying environment variables to other steps is to save them on a file
   # $BASH_ENV is just a file that runs when the a bash session starts, so we append the export command
   # Refer to the docs for details on this: https://circleci.com/docs/2.0/env-vars/
   - run: echo 'export GOROOT="/usr/local/go"' >> $BASH_ENV
   - run: echo ${GOROOT} #Now resolves to /usr/local/go
   - run: echo $BASH_ENV
   ####################################################################################

   - run: go env
      # GOBIN=""
      # GOCACHE="/home/circleci/.cache/go-build"
      # GOEXE=""
      # GOHOSTARCH="amd64"
      # GOHOSTOS="linux"
      # GOOS="linux"
      # GOPATH="/go"
      # GORACE=""
      # GOROOT="/usr/local/go"
      # GOTMPDIR=""
      # GOTOOLDIR="/usr/local/go/pkg/tool/linux_amd64"

   - run: ls ${GOROOT}/bin
   - run: ls -l ${GOPATH} #Folder has "bin" and "src" subfolders, but are empty
   - run: which go #Resolves to /usr/local/go/bin/go
   
   ####################################################################################
   #Start setting the env vars that they invoicer used
   - run: echo 'export GOPATH_HEAD="$(echo ${GOPATH}|cut -d ':' -f 1)"' >> $BASH_ENV
   - run: echo ${GOPATH_HEAD} #Not set, prints empty value
   
   - run: go build main.go #Runs correctly
