version: 2.1
orbs:
  aws-cli: circleci/aws-cli@1.0.0
jobs:
 build:
  docker:
   - image: circleci/golang:1.10
     
  steps:
   - checkout
   - setup_remote_docker
   - run: echo ${CIRCLE_PROJECT_USERNAME}
   - run: echo ${DOCKER_REPO}
   - run: echo ${CIRCLE_PROJECT_REPONAME}
   - run: echo ${GOPATH}
   - run: echo ${GOPATH_HEAD}
   - run: ls -l "${GOPATH}/bin"
   - run: go build main.go
   - run: go env
   - run: ls /usr/local/go/bin
